//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditEventFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditEventFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.AuditEventFile", typeof(AuditEventFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisniku {0} nije moguce kreirati nalog u banci. Razlog: {1}..
        /// </summary>
        internal static string CardRequestFailure {
            get {
                return ResourceManager.GetString("CardRequestFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisniku {0} je uspesno kreiran racun u banci..
        /// </summary>
        internal static string CardRequestSuccess {
            get {
                return ResourceManager.GetString("CardRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplata na racun korisnika {0} nije moguca. Razlog: {1}..
        /// </summary>
        internal static string DepositFailure {
            get {
                return ResourceManager.GetString("DepositFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} je uspesno uplatio {1} na svoj racun..
        /// </summary>
        internal static string DepositSuccess {
            get {
                return ResourceManager.GetString("DepositSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisniku {0} nije moguce resetovati pin. Razlog: {1}..
        /// </summary>
        internal static string ResetPinFailure {
            get {
                return ResourceManager.GetString("ResetPinFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} je uspesno resetovao svoj pin..
        /// </summary>
        internal static string ResetPinSuccess {
            get {
                return ResourceManager.GetString("ResetPinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisniku {0} nije moguce izdati novi sertifikat. Razlog: {1}..
        /// </summary>
        internal static string RevokeRequestFailure {
            get {
                return ResourceManager.GetString("RevokeRequestFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisniku {0} je uspesno povucen sertifikat i dodeljen novi..
        /// </summary>
        internal static string RevokeRequestSuccess {
            get {
                return ResourceManager.GetString("RevokeRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isplata sa racuna korisnika {0} nije moguca. Razlog: {1}..
        /// </summary>
        internal static string WithdrawFailure {
            get {
                return ResourceManager.GetString("WithdrawFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} je uspesno podigao sa svog naloga {1}..
        /// </summary>
        internal static string WithdrawSuccess {
            get {
                return ResourceManager.GetString("WithdrawSuccess", resourceCulture);
            }
        }
    }
}
